groups:
  - name: api-alerts
    interval: 30s
    rules:
      # High error rate
      - alert: HighErrorRate
        expr: |
          rate(http_requests_total{status_code=~"5.."}[5m]) /
          rate(http_requests_total[5m]) > 0.01
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }} for {{ $labels.route }}"

      # Critical error rate
      - alert: CriticalErrorRate
        expr: |
          rate(http_requests_total{status_code=~"5.."}[5m]) /
          rate(http_requests_total[5m]) > 0.05
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Critical error rate detected"
          description: "Error rate is {{ $value | humanizePercentage }}"

      # High latency
      - alert: HighLatency
        expr: |
          histogram_quantile(0.99,
            rate(http_request_duration_seconds_bucket[5m])
          ) > 0.5
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High API latency detected"
          description: "P99 latency is {{ $value }}s"

      # Critical latency
      - alert: CriticalLatency
        expr: |
          histogram_quantile(0.99,
            rate(http_request_duration_seconds_bucket[5m])
          ) > 1
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Critical API latency detected"
          description: "P99 latency is {{ $value }}s"

  - name: validation-alerts
    interval: 30s
    rules:
      # High validation failure rate
      - alert: HighValidationFailureRate
        expr: |
          rate(validation_requests_total{status="false"}[5m]) /
          rate(validation_requests_total[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High validation failure rate"
          description: "Validation failure rate is {{ $value | humanizePercentage }}"

      # No validation requests
      - alert: NoValidationRequests
        expr: |
          rate(validation_requests_total[10m]) == 0
        for: 15m
        labels:
          severity: info
        annotations:
          summary: "No validation requests detected"
          description: "No validation requests in the last 15 minutes"

  - name: payment-alerts
    interval: 30s
    rules:
      # Payment processing errors
      - alert: PaymentProcessingErrors
        expr: |
          rate(payment_requests_total{status="error"}[5m]) > 0
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Payment processing errors detected"
          description: "{{ $value }} payment errors per second"

  - name: system-alerts
    interval: 30s
    rules:
      # High memory usage
      - alert: HighMemoryUsage
        expr: |
          process_resident_memory_bytes / 1024 / 1024 > 1024
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage detected"
          description: "Memory usage is {{ $value }}MB"

      # High CPU usage
      - alert: HighCPUUsage
        expr: |
          rate(process_cpu_seconds_total[5m]) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected"
          description: "CPU usage is {{ $value }}%"

  - name: database-alerts
    interval: 30s
    rules:
      # Database connection pool exhausted
      - alert: DatabaseConnectionPoolExhausted
        expr: |
          pg_stat_activity_count / pg_settings_max_connections > 0.9
        for: 2m
        labels:
          severity: critical
        annotations:
          summary: "Database connection pool nearly exhausted"
          description: "Connection pool usage is {{ $value | humanizePercentage }}"

      # Slow database queries
      - alert: SlowDatabaseQueries
        expr: |
          histogram_quantile(0.99,
            rate(pg_stat_statement_duration_seconds_bucket[5m])
          ) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Slow database queries detected"
          description: "P99 query duration is {{ $value }}s"

  - name: redis-alerts
    interval: 30s
    rules:
      # Redis connection failed
      - alert: RedisConnectionFailed
        expr: |
          redis_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis connection failed"
          description: "Redis is not responding"

      # Low Redis hit rate
      - alert: LowRedisHitRate
        expr: |
          rate(redis_keyspace_hits_total[5m]) /
          (rate(redis_keyspace_hits_total[5m]) + rate(redis_keyspace_misses_total[5m])) < 0.5
        for: 10m
        labels:
          severity: info
        annotations:
          summary: "Low Redis cache hit rate"
          description: "Cache hit rate is {{ $value | humanizePercentage }}"
